Login/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "Login"

urlpatterns = [
    path('debug-db/', views.debug_database_connection, name='debug_database_connection'),
    #path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('profile/', views.profile, name='profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit-profile/<str:username>/', views.edit_profile, name='edit_profile'),
    
    # Backup URLs
    path('backups/', views.backup_list, name='backup_list'),
    path('backups/create/', views.create_backup, name='create_backup'),
    path('backups/upload/', views.upload_backup, name='upload_backup'),
    path('backups/<int:backup_id>/restore/', views.restore_backup, name='restore_backup'),
    path('backups/<int:backup_id>/download/', views.download_backup, name='download_backup'),
    path('backups/<int:backup_id>/delete/', views.delete_backup, name='delete_backup'),
]

Map/urls.py
from django.urls import path
from . import views
#from .views import user_notifications

app_name = "Map"

urlpatterns = [
    path('', views.home, name="home"),
    path('maps/', views.map_list, name='map_list'),
    #path('maps/<int:map_id>/', views.map_detail, name='map_detail'),
    path('maps/create/', views.create_map, name='create_map'),
    path('edit/<int:map_id>/', views.edit_map, name='edit_map'),
    path('maps/<int:map_id>/', views.map_detail, name='map_detail'),  # For displaying the map
    #path('maps/upload/<int:map_id>/', views.upload_files, name='upload_files'),
    #path('notifications/', user_notifications, name='user_notifications'),


    # Add more URL patterns as needed
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage


# admin.site.site_title = "Welcome to our GIS Protal"
# admin.site.site_header = "GIS Portal Admin"
# admin.site.index_title = "GIS Full Control Pannel"

def toggle_sidebar(request):
    return HttpResponse('Sidebar toggled!')

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('admin/', admin.site.urls),
    path('', include('Map.urls')),
    path('user/', include('Login.urls')),
    #path('auth/', include('django.contrib.auth.urls')),  # Temporarily disabled
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet" />
    <script src="https://unpkg.com/leaflet-fullscreen/dist/Leaflet.fullscreen.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet"> <!-- Font Awesome -->
    
    {% block head %} {% endblock %}
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    
    {% include 'navmenu.html' %}
    
    {% block body %} {% endblock %}

    <script src="{% static 'js/custom.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    {% include 'footer.html' %}
    
  </body>
</html>

templates/footer.html
<footer class="bg-body-tertiary text-center text-lg-start">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2024 Copyright:
      <a class="text-body" href="https://vnode.digital/">DTCA</a>
    </div>
    <!-- Copyright -->
  </footer>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Map Layer View {% endblock %}

{% block head %}
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
<link rel="stylesheet" href="{% static 'css/leaflet.measure.css' %}" />
<link rel="stylesheet" href="path/to/Leaflet.GlobeMini.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css" />
<link rel="stylesheet" href="{% static 'css/home.css' %}" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
<!-- Leaflet Control Geocoder CSS -->
<link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />

<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<script src="{% static 'js/leaflet.measure.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js"></script>
<!-- <script src="path/to/Leaflet.GlobeMini.js"></script> -->
<script src="https://unpkg.com/shpjs/dist/shp.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.7.1/jszip.min.js"></script>
<script src="https://api.mapbox.com/mapbox.js/plugins/leaflet-geometryutil/v0.8.0/leaflet.geometryutil.js"></script>
<script src="ttp://demos.vnode.digital/path/to/Leaflet.GlobeMini.js"></script>
<script src="{% static 'js/shpwrite.js' %}"></script>
<script src="://cdnjs.cloudflare.com/ajax/libs/togeojson/0.16.0/tokml.js"></script>
<script src="https://unpkg.com/@mapbox/shp-write@latest/shpwrite.js"></script>
<!-- Leaflet Control Geocoder JS -->
<script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>
{% endblock %}


{% block body %}

<div>
    <div class="bg overlay"
                style="background-image: url('/media/GIS-Cover-image.webp'); 
                    background-size: cover; 
                    background-position: center;
                    width: 100%; 
                    min-height: 86.8vh;">
        <div class="row" style="width: 80%; 
                                height: 100%; 
                                margin: auto; 
                                padding-top: 10vh; 
                                padding-bottom: 10vh;">
            <div class="col-12 col-md-6 h-100 d-flex justify-content-left align-items-left">
            <div >
                <div class="d-flex flex-column justify-content-left align-items-left h-100 text-">
                    <div>
                        <img class="logo" src="/media/dtca.png" alt="">
                    </div>
                    <h3 class="display-2 title">
                       <span style="color: #70F4FB;">DTCA</span> <span style="color:#dc3545">GIS Portal</span>
                    </h3>
                    <h4 class="display-6 description" >
                        <b>Connect people, locations, and data using interactive maps. Work with smart, data-driven styles and intuitive analysis tools. Share your insights with the world or specific groups.</b>
                        
                    </h4>
                    <div class="mt-5">
                        <a href="{% url 'Map:map_list' %}" class="explore-btn" style="text-decoration: none;">Explore Map</a>
                    </div>
                    
                </div>
                
            </div>
        </div>
        <div class="col-6 h-100 d-flex justify-content-center align-items-center">
         
    </div>
        </div>
</div>


<style>
    .row {
        --bs-gutter-x: 0rem;
    }
    .title {
        font-size: 45px;
        font-weight: 500; 
        color:#dc3545;
    }

    .description {
        font-size: 25px; 
        color:rgb(252, 252, 252); 
        width:70%;
    }

    .explore-btn {
    border: 1px solid white;
    color: white;
    font-size: 20px;
    background-color: transparent;
    padding: 10px 20px;
    border-radius: 20px;
}
.explore-btn:hover {
    border: 1px solid #dc3545;
    color: white;
    background-color: #dc3545;
}

.logo {
    border-radius: 100px;
    width: 130px;
    margin-bottom: 30px;
}

@media screen and (max-width: 600px) {
    .title {
        font-size: 35px;
        font-weight: 500; 
        color:#dc3545;
    }

    .description {
        font-size: 20px; 
        color:rgb(252, 252, 252); 
        width:80%;
    }

    .row {
        --bs-gutter-x: 0rem;
    }

    .h-100 {
    height: 90% !important;
}

.logo {
    border-radius: 100px;
    width: 100px;
    margin: 30px;
}

}

</style>

{% endblock %}

templates/navmenu.html
<nav style="z-index: 999" class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <a style="padding-top: 0px; padding-bottom: 0px; font-size: 2rem;" class="navbar-brand fw-bold" href="{% url 'Map:home' %}"><span style="color: #dc3545;">GIS</span> Portal</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="margin-left: 35%;">
         
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'Map:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Map:map_list' %}">Maps</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Login:dashboard' %}">Dashboard</a>
          </li>
          {% endif %}
          
        </ul>

        <div class="dropdown">
        <button class="btn btn-sm dropdown-toggle user-icon-button" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <span class="material-symbols-outlined">person</span>
        </button>
        <ul class="dropdown-menu" >
          {% if user.is_authenticated %}
          <a class="nav-link dropdown-list" href="{% url 'Login:profile' %}">Profile</a>
          <a class="nav-link dropdown-list" href="{% url 'Login:dashboard' %}">Dashboard</a>
          <a class="nav-link dropdown-list" href="{% url 'Login:user_logout' %}">Logout</a>
        {% else %}
            <a class="nav-link dropdown-list" href="{% url 'Login:user_login' %}">Login</a>
        {% endif %}
        </ul>
      </div>

      </div>

    </div>
  </nav>

  <!-- offcanvas -->
  <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel" style="z-index: 9999">
    <div class="offcanvas-header">
      <a style="padding-top: 0px; padding-bottom: 0px; font-size: 2rem;" class="navbar-brand fw-bold" href="{% url 'Map:home' %}"><span style="color: #dc3545;">GIS</span> Portal</a>
      <span><span><div class="dropdown">
        <button class="btn btn-sm dropdown-toggle user-icon-button" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <span class="material-symbols-outlined">person</span>
        </button>
        <ul class="dropdown-menu" >
          {% if user.is_authenticated %}
          <a class="nav-link dropdown-list" href="{% url 'Login:profile' %}">Profile</a>
          <a class="nav-link dropdown-list" href="{% url 'Login:dashboard' %}">Dashboard</a>
          <a class="nav-link dropdown-list" href="{% url 'Login:user_logout' %}">Logout</a>
        {% else %}
            <a class="nav-link dropdown-list" href="{% url 'Login:user_login' %}">Login</a>
        {% endif %}
        </ul>
      </div></span></span>
      <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div class="" style="margin-top: 70px!important;">
        <ul>
          <li class="">
            <a class="" aria-current="page" href="{% url 'Map:home' %}">
              <i class="fas fa-home"></i> Home
            </a>
            <hr>
          </li>
          <li class="">
            <a class="" href="{% url 'Map:map_list' %}">
              <i class="fas fa-map"></i> Maps
            </a>
            <hr>
          </li>
          {% if user.is_authenticated %}
          <li class="">
            <a class="" href="{% url 'Login:dashboard' %}">
              <i class="fas fa-tachometer-alt"></i> Dashboard
            </a>
            <hr>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
    {% include 'footer.html' %}
  </div>
  <!-- offcanvas  -->




  <style>
      /*........................................ Navbar */
      li a {
    color: #007279;
    text-decoration: none;
    font-size: 18px;
    font-weight: 500;
}

li {
  list-style-type:none;
}     
.offcanvas-header {
  background-color: #007279;
}

      .navbar {
    box-shadow: 0px 0px 8px grey;
}

.navbar-brand:hover {
  color: #dc3545;
}
.nav-item {
    font-size: 20px;
}

/* account icon */
.user-icon-button {
    margin-left: 10px;
    padding: 7px 10px;
    display: flex;
    align-items: center;
    border: 1px solid white;
    color: white;
    
}

.user-icon-button:hover {
    color: #dc3545;
    border: 1px solid white;
    background-color: white;
    
}

button, input, optgroup, select, textarea {
    font-size: 13px;
}

 .navbar>.container-fluid {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    }


.container-fluid {
    justify-content: space-around; 
    margin-left: 10%; 
    margin-right: 10%;
} 


.login {
    color:blue;
}

.navbar {
    background-color: #007279;
  }
  .nav-link{
    color: white;
  }
  .nav-link:hover{
    color: #dc3545;
  }

  .navbar-brand {
    color: white;
  }
  .dropdown-menu.show {
    padding: 10px;
}
  .dropdown-list {
    color: black;
  }
  .dropdown-list:hover {
    color: white;
    background-color: #007279;
    padding-left: 5px;
  }

  .search-btn {
  border: 1px solid white;
  color: white;
  }

  .search-btn:hover {
color: #007279;
background-color: white;
  }

  </style>
  
  